### ISSUE TITLE
Optional CAD parts heat-set-inserts #4-40 not #6-32?

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#117]
The Optional CAD parts lists a number 6 heat-set-insert for the new Arduino and back plate head mounts.  I bought both 6-32 and 4-40 for future use.  With some trepidation I tried the new technology on an old scrap rover back plate.  The holes were just the size of the 4-40 insert and too tight for the 6-32.  I drilled open one hole a couple sizes to just fit the narrow end of the 6-32.  Applying a needle tip soldering iron they both eased into place.  The 4-40 insert slipped out when pulled by a screw as the hole was a bit too large.  The 6-32 held nicely.  On the Arduino head, the 3D printed holes appear to better fit a 4-40 insert than the 6-32.  I'll wait for clarification on this before applying the soldering iron!

Jim Phelan
Mars rover project lead
USAi Labs (formerly Houston Robotics)

![45 heat-set-insert test](https://user-images.githubusercontent.com/35434147/57972589-4ac9b600-7962-11e9-9398-038b1c1f0cf7.JPG)
![46 heat-set-insert compare 4-40 vs 6-32](https://user-images.githubusercontent.com/35434147/57972591-4e5d3d00-7962-11e9-88e3-f6df32ce615f.JPG)

**Comment by ericjunkins** [comment]
The head-base CAD part calls for M2.5 inserts actually. I can eventually change these to be 6-32 or 4-40 inserts to be consistent with some of the other things bought. I generally am using metric stuff at work at so my stockpiles are generally better for metric. The arduino plate would also be made for M2.5 screws/inserts, though I believe you could get away with 4-40s in them, they should be pretty close. In general the insert will not just push into the material, it should be melting away a bit of the walls as you push it in such that it actually is inset into the plastic. Because of this M2.5 and 4-40 are pretty similar, and M3 and 6-32 are also pretty close when it comes to the inserts.

**Comment by ericjunkins** [comment]
Fixed in 71b9e5356ee9e42fb068ee36b2e46d12b22ea870
