### ISSUE TITLE
Arduino Sheild Silkscreen backwards on Connector J1

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#122]
@vssystemluba @ericjunkins 

Could y'all please post a pic of the assembled Arduino shield?  Most of it seems obvious but I need to clarify before applying solder.  I'll trade you a step-by-step album!  Thanks!

Jim Phelan
Mars rover project lead
USAi Labs (formerly Houston Robotics)

**Comment by ericjunkins** [comment]
Will do when I get a moment thanks.

**Comment by JHPHELAN** [comment]
I _believe_ it should look like THIS except I'm unsure about the orientation of the 3 connectors.
The power connector is too dark in this web view but is facing the far edge of the board
(you can save it and open it on your own computer to see it properly) :

![IMG_4830](https://user-images.githubusercontent.com/35434147/58059910-8b792900-7b34-11e9-9c09-1a91e78f16a9.JPG)

Jim Phelan
Mars rover project lead
USAi Labs (formerly Houston Robotics)

**Comment by ericjunkins** [comment]
As long as that 6 pin JST connector matches with the cable orientation you installed in your control board it is fine. See below pictures of where the 12V line is in both of them.

![image](https://user-images.githubusercontent.com/25470708/58060895-75fe0200-7b28-11e9-9ed3-306b64ec636a.png)

![image](https://user-images.githubusercontent.com/25470708/58060952-bfe6e800-7b28-11e9-9485-11004c730d82.png)

It also occured to me that the silkscreen is backwards on the J1 connector on the arduino shield. That was initially in a different location and upon moving it the silkscreen didn't get updated correctly. So that is mirror flipped as you can see below

![image](https://user-images.githubusercontent.com/25470708/58060899-7f876a00-7b28-11e9-9786-7c06aa7fb6d3.png)

**Comment by JHPHELAN** [comment]
@ericjunkins Based on your circuits above, I assembled the Arduino shield as below.  
The only difference to my sample above is reversing the JST connector to face outward.  
Looks like we need a Rev 2 of the PCBs with the silkscreen reversals corrected & showing the key notches on the silkscreens to avoid confusion.  If there was a way to indicate on the PCB which way the header pins go, that would help too.

![IMG_4835](https://user-images.githubusercontent.com/35434147/58140202-d44be300-7c03-11e9-85bb-2b36498640f6.JPG)

![IMG_4836](https://user-images.githubusercontent.com/35434147/58140210-da41c400-7c03-11e9-9b12-6c15abd3d0db.JPG)

![IMG_4839](https://user-images.githubusercontent.com/35434147/58141001-54277c80-7c07-11e9-9440-b706def56714.JPG)

![IMG_4840](https://user-images.githubusercontent.com/35434147/58141005-5c7fb780-7c07-11e9-82f1-95f8a469c333.JPG)

Jim Phelan
Mars rover project lead
USAi Labs (formerly Houston Robotics)

**Comment by vssystemluba** [comment]
@JHPHELAN thanks for helping to add clarity here.  I've pushed a change to the silk screen (d2a88c6) that flips the labels which hopefully make things a little clearer.
