### ISSUE TITLE
Step 1.5 (6) in the mechanical integration is a duplicate of Step 2.2.3 in the Body Build

### ISSUE THREAD

**Issue by toebes** [nasa-jpl/open-source-rover#145]
Both steps are for putting in the differential pivot joint.  It makes more sense to be in the body build, so it should be taken out of the mechanical integration.

**Comment by vssystemluba** [comment]
This was also noted in #148 and was fixed in 4590fbd.  It makes more sense to do the integration step last, since the clamps need to be put on the differential pivot partway through its installation.  The step has therefore been moved to the Mechanical Integration doc and removed from the Body Build.
