### ISSUE TITLE
Update Body Build Doc images to no longer include the differential pivot clamp assembly

### ISSUE THREAD

**Issue by mikcox** [nasa-jpl/open-source-rover#152]

**Comment by vssystemluba** [comment]
@toebes I'd love to use photos from the new Onshape model for this if possible.

However, since we moved the duplicated steps related to the differential pivot out of the body build doc, those parts need to be edited out of the Onshape model.  Would you mind clearing the old steps 2.2.2 and 2.3 out of the body build assembly in Onshape and making sure the assemblies are still clean as you intended them to be?  I didn't want to dig too far into the model myself for fear of breaking your beautiful creation.  :)

**Comment by toebes** [comment]
I've fixed the model deleting the old steps.  Let me know if you want any additional slicing and dicing of it.

**Comment by vssystemluba** [comment]
The model looks good.  I'll update the photos in our build doc based on the new model steps later on today.  :)

Thanks for the rapid update!
