### ISSUE TITLE
9 x 12 top and bottom ServoCity plates discontinued

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/open-source-rover#250]
@dcschooley found out they are discountinued.

* One idea is to replace with two 9 x 6 plates and connectors.
* Better: use a laser cutter

**Comment by Achllle** [comment]
* YouDoItElectronics [still has it in stock](https://www.youdoitelectronics.com/actobotics-9-x-12-aluminum-pattern-plate-585006)
* British website [still has it in stock](https://www.active-robots.com/9-x-12-aluminum-pattern-plate.html) (for now)

These will likely be out of stock as well soon

**Comment by dcschooley** [comment]
Using two 4.5x12 inch plates is doable. The hole for the rocker-bogie pivot will be on the seam, which means you are grinding the hole instead of drilling it. Materials for cutting the top and bottom pieces out of acrylic would cost $20-$35, depending on color and where you buy it. (You would need two 12x20 sheets.) With another sheet you can do the entire body in acrylic. I don't know what it would cost to have someone like Sculpteo make them. 


![IMG_3891](https://user-images.githubusercontent.com/59415821/109101451-54ae4a80-76ec-11eb-8518-e01decc56b54.png)
