### ISSUE TITLE
`master_parts_list_raw.csv` has `crlf` line endings

### ISSUE THREAD

**Issue by sethfischer** [nasa-jpl/open-source-rover#311]
`master_parts_list_raw.csv` has `crlf` line endings. Contributors can inadvertently change the line endings for every line of the file when intending to edit only a few lines.

Two proposals to mitigate this are:

## Option 1 #312 superseded by b5295acc83eda2de8eafed4b60b9c0142b2d4c67

~~Specify in `.editorconfig` that `master_parts_list_raw.csv` has `crlf` line endings. Other files have `lf` line endings.~~

```ini
root = true

[*]
end_of_line = lf
insert_final_newline = true

[parts_list/master_parts_list_raw.csv]
end_of_line = crlf
```

_Originally posted by @sethfischer in https://github.com/nasa-jpl/open-source-rover/issues/298#issuecomment-853584639_

## Option 2 #320

Commit `master_parts_list_raw.csv` to the repo with Unix line endings and suggest contributors use [Git's `core.autocrlf`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf) setting.

The use of this setting could be documented in a file such as `.github/CONTRIBUTING.md` or `CONTRIBUTING.md`.

I believe option 2 would be a more typical approach when when contributors use a mix of operating systems.

**Comment by dcschooley** [comment]
Using Git's core.autocrlf setting might be best, but the parameters should be defined because it looks like they are different depending on the destination OS. I'm using MacOS, which uses the correct line endings, but I still managed to screw this up because Excel isn't always clear as to what it is doing and I am enough of a newb to not know to check it. It would be nice if git/GitHub was smart enough to handle this intelligently.
