### ISSUE TITLE
Making OSR space-rated

### ISSUE THREAD

**Issue by capsulecorplab** [nasa-jpl/open-source-rover#71]
This is more of a hypothetical discussion than an actual feature request, but what modifications would need to be made for OSR to be considered "space-rated"?

**Comment by vssystemluba** [comment]
The short story is that the OSR is nowhere near space-ready and we don't have any intention of making it so.  It's meant as an educational tool, not a functioning Mars rover!!

The longer story is that it's REALLY _REALLY_ **_REALLY_** hard to make things "space-rated".  That's why it's so expensive.  The simplest guaranteed-functioning, Mars-rated robot is basically Pathfinder, the first one that JPL built.  A few of the quick issues that come to mind for "space-rating" the open source rover would be:
- Radiation: all the electronics on the OSR would fry pretty quickly once they were outside of Earth's atmosphere and exposed to solar radiation (much less the additional radiation from whatever planetary body it landed on).  For reference, the flight computer on MSL (Curiosity, the current top of the line Mars rover) is a Rad750 (single core, 100-200MHz, or ~1/10 as powerful as a raspberry pi).
- Vibration: the Open Source Rover wasn't really built to go road tripping.  If you vibrate and shake it for long enough, screws fall out, electronics get disconnected, and things come apart.  This can't happen for something riding on a rocket!
- Temperature: The components on the Open Source Rover function well around room temperature on Earth.  You better believe that "room temperature" in orbit or on Mars is quite different!  Even on the Curiosity rover, the large temperature swings on Mars mean that it's really only safe to drive the rover heavily during the daytime.

... the above are the first 3 things that I thought of.  There are probably hundreds of challenges to overcome that I haven't even thought of yet.  The Mars rover program cost ~$2.5 billion... this one is $2,500.  Understandably, the rovers therefore have very different capabilities.
