### ISSUE TITLE
REV-C Revisions to be made

### ISSUE THREAD

**Issue by ericjunkins** [nasa-jpl/open-source-rover#91]
I've received the REV-C board, and these are the following revisions to be made:

  * All coupling capacitors are connected to the voltage side of powering components instead of GND. They will all need to be fixed for this.
  * Need to add a USB connector on 5V line to run to the 4 position powered USB hub (optional)
  * Need to add a Barrel Jack connector to board for 12V powered USB hub (optional)
    * https://www.digikey.com/product-detail/en/tensility-international-corp/10-01776/839-1242-ND/5638252
    * https://www.digikey.com/product-detail/en/tensility-international-corp/10-02382/839-1312-ND/6593491
  * 12 V regulator mounting holes are 90 deg offset from pins, need to update mounting footprint

**Comment by philwil** [comment]
I built most of one of these over the weekend 3/2/2019. I got 5 PCb's from JPL. 
They also sent me 10 of the arduino shields !! 
I only plan to use two of each of them so the others are up for grabs !!
I have yet to start testing since some components were out of stock.
Are there any plans for a REV-C.1 or a REV-D with the capacitor problem fixed ?
 If not I'll start building my second board.
I am also preparing a list of suggestions to add to Eric's list above.
I can focus on completing that list if you are trying to get the next rev out.
Thanks for the effort. This is a fun project.

**Comment by ericjunkins** [comment]
I have a rev-d board ready to be populated, i'm just waiting on a few components from digikey still. If you want to test yours you'll have to replace all the caps with jumpers instead. 

The arduino hat board works but I realized the screw terminal pins run into the USB port and would short, i clipped the pins on the bottom and put capton tape over.  I have a 2nd rev of that as well. 

I will post the updated files as soon as I get to testing the new rev d board,  hopefully in the next few days

**Comment by philwil** [comment]
Thanks, I'll hold off building the second board until I get your reworked files.

**Comment by philwil** [comment]
HI Eric,
Some more feedback.
Got the two power supplies for the REV-C board last night.
The 5V PSU  fits OK but I can only use one spacer The other hits the
connector. I can use an extended bolt to hold it down.
The 12V PSU seems to have the mounting holes reversed.
I assume that both of these power supplies fit under the board.

I am planning on using much cheaper ten turn pots for the absolute encoders
I can get the larger bore pinion gears but am unable to use the grub screw
to secure them.
Looks like I'll have to glue the pinions on the pot shaft or shave a flat
on the shaft to give the grub screw enough thread to hold.
It looks like full range on the steering motors will use about 4.5 turns.
This almost gives us 2V if put 5V across the pots
I'll look at adding variable gain and offset to the op amps to get the 2V
range needed.

...

**Comment by philwil** [comment]
On the encoders

I would much rather have the option to use the relative encoders on the
motors. ( I have them fitted) and then use the potentiometers to get some
form of absolute position.
Possibly use a MCP3008 for PI analog in .. dont populate it if you dont
need it. You would also get 4 extra spare analog inputs.
Another option would be to use a level detector on the potentiometer to
trigger detecting an absolute location.
If you use the potentiomenter you will have to solve the alignment problem.
You could use a trim pot on the board.
I like that idea since it is easy to set up.
Then we could use the relative encoders together with the potentiometer to
get the steering setup.
You bet I am willing to help here.

...

**Comment by ericjunkins** [comment]
@philwil Sorry for the long delay on messaging back. I have though about that exact thing, using quadrature encoders on the corner motor and a potentiometer to sync the position and recheck occasionally if there is slip in the corner system. I'll have to think about the best way to build that into the board to support both, not necessarily an easy task at the moment. 

All revisions have been made and tested with commit 30e20808a101ab2fc350cca8feb0b62c04a7547c so im going to close this issue, feel free to continue the discussion though

**Comment by philwil** [comment]
Thanks for the update.
I am busy on another small project at the moment but was just about to
place another pcb order.
I'll look at manually wiring the corner motor encoders at this time.
I also am thinking of an ADS1115 encoder to pick up the potentiometer
readings.
Using those for another project.
  I'll let you know when I order the new boards.
